# Generated by Django 5.1 on 2025-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
