# Generated by Django 5.1 on 2025-04-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0003_medicaldepartment_remove_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medical_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booked_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MedicalDepartment',
        ),
    ]
