# Generated by Django 5.2.1 on 2025-06-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0004_alter_doctor_medical_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='available',
            new_name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='p_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='p_phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='managementapp.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='managementapp.doctor'),
        ),
    ]
